spring.application.name=LoverFlower

spring.datasource.url=jdbc:postgresql://localhost:5432/flower-lover
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true